### ISSUE TITLE
build.sh - missing .mk files

### ISSUE THREAD

**Issue by mj8ac** [vortex314/Vertx-ESP8266#2]
Hi Liven, 

I think I am almost there with the compilation...! Thank you for adding a build script, it got as far as line 32 where it tries to run `make flash` in the vertx-esp8266 directory. It throws this error:

`jonny@jonny-VirtualBox:~/Vertx-ESP8266/vertx-esp8266$ make flash
../esp-open-rtos/common.mk:223: ../esp-open-rtos/../ArduinoJson/component.mk: No such file or directory
make: *** No rule to make target '../esp-open-rtos/../ArduinoJson/component.mk'. Stop.
`
I think I may also be missing some dependencies still as the Makefile in the vertx-esp8266 is looking for an extras directory which doesn't exists. Should I create it?

Thanks for your help. 

Jonny

**Comment by vortex314** [comment]
Hi Jonny,
I think I know what's missing. The way the esp-open-rtos build works, is that it expects a component.mk in each folder it needs to include in the build. I probably created a component.mk in the ArduinoJson folder, it's not part of ArduinoJson repository itself. I'll pick it up and make it part of the build script.
The 'extras' you shouldn't worry about as they are part of the modules included in the esp-open-rtos you cloned from github.
I'll check later this evening. 
Lieven

**Comment by vortex314** [comment]
content of the component.mk should be:

#

# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in direc
' to include path.)
# COMPONENT_ADD_INCLUDEDIRS=.
# CXXFLAGS +="-DESP32_IDF=1"
# Component makefile for extras/ArduinoJson

# expected anyone using bmp driver includes it as 'ArduinoJson/M
INC_DIRS += $(ArduinoJson_ROOT)..  $(ArduinoJson_ROOT)

# args for passing into compile rule generation
ArduinoJson_SRC_DIR =  $(ArduinoJson_ROOT)

$(eval $(call component_compile_rules,ArduinoJson))

didn't have time to update build

**Comment by vortex314** [comment]
Hi Jonny,
the content of this file should be as mentioned below. This should be copied into a file called 'component.mk' in the directory ArduinoJson.
Hope this helps,
Lieven
```
#
# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in direc
' to include path.)
# COMPONENT_ADD_INCLUDEDIRS=.
# CXXFLAGS +="-DESP32_IDF=1"
# Component makefile for extras/ArduinoJson

# expected anyone using bmp driver includes it as 'ArduinoJson/M
INC_DIRS += $(ArduinoJson_ROOT)..  $(ArduinoJson_ROOT)

# args for passing into compile rule generation
ArduinoJson_SRC_DIR =  $(ArduinoJson_ROOT)

$(eval $(call component_compile_rules,ArduinoJson))```

**Comment by mj8ac** [comment]
Amazing!! It compiled and flashed my Wemos Mini Pro!! I had to set INCLUDE_eTaskGetState to 1 in FreeRTOS.h. Once I did that it compiled and flashed! 

Thanks your help!

**Comment by vortex314** [comment]
Jonny,
thanks for the feedback. Success with your project.

Lieven

**Comment by mj8ac** [comment]
Thank you Lieven,

I will keep you updated. I am trying to make a system that can track
someone sprinting over a 100m distance.

Have you deployed your positioning system in the field?

Kind Regards
Jonny

**Comment by vortex314** [comment]
I have 4-5 anchors running for the moment inside, to check on stability , looking good so far.
For the rest working on my full-automatic lawnmower that will use the positioning system.

**Comment by mj8ac** [comment]
OK amazing that sounds good.

The lawn mower project is cool, autonomous navigation is hot area right now
- did you consider using a neural network based solution for the mower
navigation? Like in autonomous RC projects? I guess the additional sensors
would make that approach much more expensive... lidar, camera, nvidia
jetson etc... Whereas with your system it is arduino based?

Where do I modify the system.host property to set the hostname of each
anchor? I have set my environment variables like so for SSID and PSWD:

export SSID=\\\"myssid\\\"
export PSWD=\\\"mypswd\\\"

Is it the right syntax?

Kind Regards,
Jonny

**Comment by vortex314** [comment]
The system.host property can be changed via telnet. 
Find in the logs , the following lines : 
```
I|8398 esp2 -|   Wifi.cpp:  70 | Wifi status =1 , retries left: 28
ip:192.168.0.229,mask:255.255.255.0,gw:192.168.0.1
I|9398 esp2 -| EventBus.cpp:  57 |  publish event : 'wifi/connected'
I|9399 esp2 -|   Wifi.cpp:  89 | WiFi: Connected
I|9400 esp2 -|   Mdns.cpp:  18 |  SNTP wifi connected 
```
Use the IP address indicated ( will be different on your network ) and connect through telnet. The above device already received another name, the default name is "ESP-XXXXXXXXXX", where XXXXXXXX stands for the mac address.

```
 telnet 192.168.0.229
Trying 192.168.0.229...
Connected to 192.168.0.229.
Escape character is '^]'.

esp2 $ config show 
{
  "system": {
    "host": "esp2"
  },
  "dwm1000": {
    "role": "N",
    "x": 1000,
    "y": 2000
  },
  "telnet": {
    "port": 23
  },
  "wifi": {
    "ssid": "yourSSID",
    "pswd": "yourPassword"
  }
}
esp2 $ config set system host esp222
 done - system host=esp222 
esp2 $ config show
{
  "system": {
    "host": "esp222"
  },
  "dwm1000": {
    "role": "N",
    "x": 1000,
    "y": 2000
  },
  "telnet": {
    "port": 23
  },
  "wifi": {
    "ssid": "yourSSID",
    "pswd": "yourPassword"
  }
}
esp2 $ config save
 config saved.
esp2 $ system reset   ==> this resets the system, push reset  button could be necessary
```
Add in your linux .profile ( don't forget to logout/login before this takes effect )
```
SSID=\\\"yourSSID\\\"
PSWD=\\\"yourPassword\\\"
```
Hope this helps.
Neural network is in the pipeline, but first get the stuff running.
Positioning will be a combination of DWM1000, compass and tilt sensor + tachometer for speed, this should give the complete vector of movement and location.
